FROM quay.io/astronomer/astro-runtime:12.6.0
# Install Apache Airflow providers for Snowflake and Google Cloud
RUN pip install apache-airflow-providers-snowflake
RUN pip install apache-airflow-providers-google