name: Terraform Snowflake

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        env:
          TF_VAR_account_name: ${{ secrets.TF_VAR_ACCOUNT_NAME }}
          TF_VAR_database: ${{ secrets.TF_VAR_DATABASE }}
          TF_VAR_organization_name: ${{ secrets.TF_VAR_ORGANIZATION_NAME }}
          TF_VAR_password: ${{ secrets.TF_VAR_PASSWORD }}
          TF_VAR_schema: ${{ secrets.TF_VAR_SCHEMA }}
          TF_VAR_user: ${{ secrets.TF_VAR_USER }}
        run: cd terraform/snowflake && terraform init -input=false

      - name: Plan Terraform
        env:
          TF_VAR_account_name: ${{ secrets.TF_VAR_ACCOUNT_NAME }}
          TF_VAR_database: ${{ secrets.TF_VAR_DATABASE }}
          TF_VAR_organization_name: ${{ secrets.TF_VAR_ORGANIZATION_NAME }}
          TF_VAR_password: ${{ secrets.TF_VAR_PASSWORD }}
          TF_VAR_schema: ${{ secrets.TF_VAR_SCHEMA }}
          TF_VAR_user: ${{ secrets.TF_VAR_USER }}
        run: cd terraform/snowflake && terraform plan -input=false

      - name: Apply Terraform
        if: github.event.inputs.apply == 'true'
        env:
          TF_VAR_account_name: ${{ secrets.TF_VAR_ACCOUNT_NAME }}
          TF_VAR_database: ${{ secrets.TF_VAR_DATABASE }}
          TF_VAR_organization_name: ${{ secrets.TF_VAR_ORGANIZATION_NAME }}
          TF_VAR_password: ${{ secrets.TF_VAR_PASSWORD }}
          TF_VAR_schema: ${{ secrets.TF_VAR_SCHEMA }}
          TF_VAR_user: ${{ secrets.TF_VAR_USER }}
        run: cd terraform/snowflake && terraform apply -auto-approve -input=false
